/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","cs",{title:"Instrukce pro přistupnost",contents:"Obsah napovědy. Pro uzavřeni tohoto dialogu stiskněte klavesu ESC.",legend:[{name:"Obecne",items:[{name:"Panel nastrojů editoru",legend:"Stiskněte${toolbarFocus} k prochazeni panelu nastrojů. Přejděte na dalši a předchozi skupiny pomoci TAB a SHIFT+TAB. Přechod na dalši a předchozi tlačitko panelu nastrojů je pomoci ŠIPKA VPRAVO nebo ŠIPKA VLEVO. Stisknutim mezerniku nebo klavesy ENTER tlačitko aktivujete."},{name:"Dialogove okno editoru",
legend:"Uvnitř dialogoveho okna stiskněte TAB pro přesunuti na dalši prvek okna, stiskněte SHIFT+TAB pro přesun na předchozi prvek okna, stiskněte ENTER pro odeslani dialogu, stiskněte ESC pro jeho zrušeni. Pro dialogova okna, ktera maji mnoho karet stiskněte ALT+F10 pro zaměřeni seznamu karet, nebo TAB, pro posun podle pořadi karet.Při zaměřeni seznamu karet se můžete jimi posouvat pomoci ŠIPKY VPRAVO a VLEVO."},{name:"Kontextove menu editoru",legend:"Stiskněte ${contextMenu} nebo klavesu APPLICATION k otevřeni kontextoveho menu. Pak se přesuňte na dalši možnost menu pomoci TAB nebo ŠIPKY DOLŮ. Přesuňte se na předchozi možnost pomoci  SHIFT+TAB nebo ŠIPKY NAHORU. Stiskněte MEZERNIK nebo ENTER pro zvoleni možnosti menu. Podmenu současne možnosti otevřete pomoci MEZERNIKU nebo ENTER či ŠIPKY DOLEVA. Kontextove menu uzavřete stiskem ESC."},
{name:"Rameček seznamu editoru",legend:"Uvnitř ramečku seznamu se přesunete na dalši položku menu pomoci TAB nebo ŠIPKA DOLŮ. Na předchozi položku se přesunete SHIFT+TAB nebo ŠIPKA NAHORU. Stiskněte MEZERNIK nebo ENTER pro zvoleni možnosti seznamu. Stiskněte ESC pro uzavřeni seznamu."},{name:"Lišta cesty prvku v editoru",legend:"Stiskněte ${elementsPathFocus} pro prochazeni lišty cesty prvku. Na dalši tlačitko prvku se přesunete pomoci TAB nebo ŠIPKA VPRAVO. Na předchozi tlačitko se přesunete pomoci SHIFT+TAB nebo ŠIPKA VLEVO. Stiskněte MEZERNIK nebo ENTER pro vybrani prvku v editoru."}]},
{name:"Přikazy",items:[{name:" Přikaz Zpět",legend:"Stiskněte ${undo}"},{name:" Přikaz Znovu",legend:"Stiskněte ${redo}"},{name:" Přikaz Tučne",legend:"Stiskněte ${bold}"},{name:" Přikaz Kurziva",legend:"Stiskněte ${italic}"},{name:" Přikaz Podtrženi",legend:"Stiskněte ${underline}"},{name:" Přikaz Odkaz",legend:"Stiskněte ${link}"},{name:" Přikaz Skryt panel nastrojů",legend:"Stiskněte ${toolbarCollapse}"},{name:"Přikaz pro přistup k předchozimu prostoru zaměřeni",legend:"Stiskněte ${accessPreviousSpace} pro přistup k nejbližšimu nedosažitelnemu prostoru zaměřeni před střiškou, napřiklad: dva přilehle prvky HR. Pro dosaženi vzdalenych prostorů zaměřeni tuto kombinaci klaves opakujte."},
{name:"Přikaz pro přistup k dalšimu prostoru zaměřeni",legend:"Stiskněte ${accessNextSpace} pro přistup k nejbližšimu nedosažitelnemu prostoru zaměřeni po střišce, napřiklad: dva přilehle prvky HR. Pro dosaženi vzdalenych prostorů zaměřeni tuto kombinaci klaves opakujte."},{name:" Napověda přistupnosti",legend:"Stiskněte ${a11yHelp}"}]}],tab:"Tabulator",pause:"Pauza",capslock:"Caps lock",escape:"Escape",pageUp:"Stranka nahoru",pageDown:"Stranka dolů",leftArrow:"Šipka vlevo",upArrow:"Šipka nahoru",
rightArrow:"Šipka vpravo",downArrow:"Šipka dolů",insert:"Vložit",leftWindowKey:"Leva klavesa Windows",rightWindowKey:"Prava klavesa Windows",selectKey:"Vyberte klavesu",numpad0:"Numericka klavesa 0",numpad1:"Numericka klavesa 1",numpad2:"Numericka klavesa 2",numpad3:"Numericka klavesa 3",numpad4:"Numericka klavesa 4",numpad5:"Numericka klavesa 5",numpad6:"Numericka klavesa 6",numpad7:"Numericka klavesa 7",numpad8:"Numericka klavesa 8",numpad9:"Numericka klavesa 9",multiply:"Numericka klavesa nasobeni",
add:"Přidat",subtract:"Numericka klavesa odečitani",decimalPoint:"Desetinna tečka",divide:"Numericka klavesa děleni",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num lock",scrollLock:"Scroll lock",semiColon:"Střednik",equalSign:"Rovnitko",comma:"Čarka",dash:"Pomlčka",period:"Tečka",forwardSlash:"Lomitko",graveAccent:"Přizvuk",openBracket:"Otevřena hranata zavorka",backSlash:"Obracene lomitko",closeBracket:"Uzavřena hranata zavorka",
singleQuote:"Jednoducha uvozovka"});