/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","de-ch",{title:"Barrierefreiheitinformationen",contents:"Hilfeinhalt. Um den Dialog zu schliessen die Taste ESC drucken.",legend:[{name:"Allgemein",items:[{name:"Editorwerkzeugleiste",legend:"Drucken Sie ${toolbarFocus} auf der Symbolleiste. Gehen Sie zur nachsten oder vorherigen Symbolleistengruppe mit TAB und SHIFT+TAB. Gehen Sie zur nachsten oder vorherigen Symbolleiste auf die Schaltflache mit dem RECHTS- oder LINKS-Pfeil. Drucken Sie die Leertaste oder Eingabetaste, um die Schaltflache in der Symbolleiste aktivieren."},
{name:"Editordialog",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Editor-Kontextmenu",legend:"Durcken Sie ${contextMenu} oder die Anwendungstaste um das Kontextmenu zu offnen. Man kann die Pfeiltasten zum Wechsel benutzen. Mit der Leertaste oder der Enter-Taste kann man den Menupunkt aufrufen. Schliessen Sie das Kontextmenu mit der ESC-Taste."},
{name:"Editor-Listenbox",legend:"Innerhalb einer Listenbox kann man mit der TAB-Taste oder den Pfeilrunter-Taste den nachsten Menueintrag wahlen. Mit der SHIFT+TAB Tastenkombination oder der Pfeilhoch-Taste gelangt man zum vorherigen Menupunkt. Mit der Leertaste oder Enter kann man den Menupunkt auswahlen. Drucken Sie ESC zum Verlassen des Menus."},{name:"Editor-Elementpfadleiste",legend:"Drucken Sie ${elementsPathFocus} um sich durch die Pfadleiste zu bewegen. Um zum nachsten Element zu gelangen drucken Sie TAB oder die Pfeilrechts-Taste. Zum vorherigen Element gelangen Sie mit der SHIFT+TAB oder der Pfeillinks-Taste. Drucken Sie die Leertaste oder Enter um das Element auszuwahlen."}]},
{name:"Befehle",items:[{name:"Ruckgangig-Befehl",legend:"Drucken Sie ${undo}"},{name:"Wiederherstellen-Befehl",legend:"Drucken Sie ${redo}"},{name:"Fettschrift-Befehl",legend:"Drucken Sie ${bold}"},{name:"Kursiv-Befehl",legend:"Drucken Sie ${italic}"},{name:"Unterstreichen-Befehl",legend:"Drucken Sie ${underline}"},{name:"Link-Befehl",legend:"Drucken Sie ${link}"},{name:"Werkzeugleiste einklappen-Befehl",legend:"Drucken Sie ${toolbarCollapse}"},{name:"Zugang bisheriger Fokussierung Raumbefehl ",legend:"Drucken Sie ${accessPreviousSpace}  auf den am nachsten nicht erreichbar Fokus-Abstand vor die Einfugemarke zugreifen: zwei benachbarte HR-Elemente. Wiederholen Sie die Tastenkombination um entfernte Fokusraume zu erreichen. "},
{name:"Zugang nachster Schwerpunkt Raumbefehl ",legend:"Drucken Sie $ { accessNextSpace }, um den nachsten unerreichbar Fokus Leerzeichen nach dem Cursor zum Beispiel auf: zwei benachbarten HR Elemente. Wiederholen Sie die Tastenkombination zum fernen Fokus Bereiche zu erreichen. "},{name:"Eingabehilfen",legend:"Drucken Sie ${a11yHelp}"}]}],tab:"Tab",pause:"Pause",capslock:"Feststell",escape:"Escape",pageUp:"Bild auf",pageDown:"Bild ab",leftArrow:"Linke Pfeiltaste",upArrow:"Obere Pfeiltaste",rightArrow:"Rechte Pfeiltaste",
downArrow:"Untere Pfeiltaste",insert:"Einfugen",leftWindowKey:"Linke Windowstaste",rightWindowKey:"Rechte Windowstaste",selectKey:"Taste auswahlen",numpad0:"Ziffernblock 0",numpad1:"Ziffernblock 1",numpad2:"Ziffernblock 2",numpad3:"Ziffernblock 3",numpad4:"Ziffernblock 4",numpad5:"Ziffernblock 5",numpad6:"Ziffernblock 6",numpad7:"Ziffernblock 7",numpad8:"Ziffernblock 8",numpad9:"Ziffernblock 9",multiply:"Multiplizieren",add:"Addieren",subtract:"Subtrahieren",decimalPoint:"Punkt",divide:"Dividieren",
f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Ziffernblock feststellen",scrollLock:"Rollen",semiColon:"Semikolon",equalSign:"Gleichheitszeichen",comma:"Komma",dash:"Bindestrich",period:"Punkt",forwardSlash:"Schragstrich",graveAccent:"Gravis",openBracket:"Offnende eckige Klammer",backSlash:"Ruckwartsgewandter Schragstrich",closeBracket:"Schliessende eckige Klammer",singleQuote:"Einfaches Anfuhrungszeichen"});