/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","es",{title:"Instrucciones de accesibilidad",contents:"Ayuda. Para cerrar presione ESC.",legend:[{name:"General",items:[{name:"Barra de herramientas del editor",legend:'Presiona ${toolbarFocus} para navegar por la barra de herramientas. Para moverse por los distintos grupos de herramientas usa las teclas TAB y MAY+TAB. Para moverse por las distintas herramientas usa FLECHA DERECHA o FECHA IZQUIERDA. Presiona "espacio" o "intro" para activar la herramienta.'},{name:"Editor de dialogo",
legend:"Dentro del dialogo, presione TAB para navegar a los siguientes elementos de dialogo, presione SHIFT+TAB para moverse a los anteriores elementos de dialogo, presione ENTER para enviar el dialogo, presiona ESC para cancelar el dialogo. Cuando el dialogo tiene multiples pestanas, la lista de pestanas puede ser abarcada con ALT + F10 or con TAB como parte del orden de pestanas del dialogo. ECon la pestana enfocada, puede moverse a la siguiente o anterior pestana con las FLECHAS IZQUIRDA y DERECHA respectivamente."},
{name:"Editor del menu contextual",legend:"Presiona ${contextMenu} o TECLA MENU para abrir el menu contextual. Entonces muevete a la siguiente opcion del menu con TAB o FLECHA ABAJO. Muevete a la opcion previa con SHIFT + TAB o FLECHA ARRIBA. Presiona ESPACIO o ENTER para seleccionar la opcion del menu. Abre el submenu de la opcion actual con ESPACIO o ENTER o FLECHA DERECHA. Regresa al elemento padre del menu con ESC o FLECHA IZQUIERDA. Cierra el menu contextual con ESC."},{name:"Lista del Editor",
legend:"Dentro de una lista, te mueves al siguiente elemento de la lista con TAB o FLECHA ABAJO. Te mueves al elemento previo de la lista con SHIFT+TAB o FLECHA ARRIBA. Presiona ESPACIO o ENTER para elegir la opcion de la lista. Presiona ESC para cerrar la lista."},{name:"Barra de Ruta del Elemento en el Editor",legend:"Presiona ${elementsPathFocus} para navegar a los elementos de la barra de ruta. Te mueves al siguiente elemento boton con TAB o FLECHA DERECHA. Te mueves al boton previo con SHIFT+TAB o FLECHA IZQUIERDA. Presiona ESPACIO o ENTER para seleccionar el elemento en el editor."}]},
{name:"Comandos",items:[{name:"Comando deshacer",legend:"Presiona ${undo}"},{name:"Comando rehacer",legend:"Presiona ${redo}"},{name:"Comando negrita",legend:"Presiona ${bold}"},{name:"Comando italica",legend:"Presiona ${italic}"},{name:"Comando subrayar",legend:"Presiona ${underline}"},{name:"Comando liga",legend:"Presiona ${liga}"},{name:"Comando colapsar barra de herramientas",legend:"Presiona ${toolbarCollapse}"},{name:"Comando accesar el anterior espacio de foco",legend:"Presiona ${accessPreviousSpace} para accesar el espacio de foco no disponible mas cercano anterior al cursor, por ejemplo: dos elementos HR adyacentes. Repite la combinacion de teclas para alcanzar espacios de foco distantes."},
{name:"Comando accesar el siguiente spacio de foco",legend:"Presiona ${accessNextSpace} para accesar el espacio de foco no disponible mas cercano despues del cursor, por ejemplo: dos elementos HR adyacentes. Repite la combinacion de teclas para alcanzar espacios de foco distantes."},{name:"Ayuda de Accesibilidad",legend:"Presiona ${a11yHelp}"}]}],tab:"Tabulador",pause:"Pausa",capslock:"Bloq. Mayus.",escape:"Escape",pageUp:"Regresar Pagina",pageDown:"Avanzar Pagina",leftArrow:"Flecha Izquierda",upArrow:"Flecha Arriba",
rightArrow:"Flecha Derecha",downArrow:"Flecha Abajo",insert:"Insertar",leftWindowKey:"Tecla Windows Izquierda",rightWindowKey:"Tecla Windows Derecha",selectKey:"Tecla de Seleccion",numpad0:"Tecla 0 del teclado numerico",numpad1:"Tecla 1 del teclado numerico",numpad2:"Tecla 2 del teclado numerico",numpad3:"Tecla 3 del teclado numerico",numpad4:"Tecla 4 del teclado numerico",numpad5:"Tecla 5 del teclado numerico",numpad6:"Tecla 6 del teclado numerico",numpad7:"Tecla 7 del teclado numerico",numpad8:"Tecla 8 del teclado numerico",
numpad9:"Tecla 9 del teclado numerico",multiply:"Multiplicar",add:"Sumar",subtract:"Restar",decimalPoint:"Punto Decimal",divide:"Dividir",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Punto y coma",equalSign:"Signo de Igual",comma:"Coma",dash:"Guion",period:"Punto",forwardSlash:"Diagonal",graveAccent:"Acento Grave",openBracket:"Abrir llave",backSlash:"Diagonal Invertida",closeBracket:"Cerrar llave",
singleQuote:"Comillas simples"});