/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","fr",{title:"Instructions d'accessibilite",contents:"Contenu de l'aide. Pour fermer cette fenetre, appuyez sur la touche Echap.",legend:[{name:"General",items:[{name:"Barre d'outils de l'editeur",legend:"Appuyer sur ${toolbarFocus} pour acceder a la barre d'outils. Se deplacer vers le groupe suivant ou precedent de la barre d'outils avec les touches Tab et Maj+Tab. Se deplacer vers le bouton suivant ou precedent de la barre d'outils avec les touches Fleche droite et Fleche gauche. Appuyer sur la barre d'espace ou la touche Entree pour activer le bouton de barre d'outils."},
{name:"Fenetre de l'editeur",legend:"Dans une boite de dialogue, appuyer sur Tab pour passer a l'element suivant, appuyer sur Maj+Tab pour passer a l'element precedent, appuyer sur Entree pour valider, appuyer sur Echap pour annuler. Quand une boite de dialogue possede des onglets, la liste peut etre atteinte avec Alt+F10 ou avec Tab. Dans la liste des onglets, se deplacer vers le suivant et le precedent avec les touches Fleche droite et Fleche gauche respectivement."},{name:"Menu contextuel de l'editeur",
legend:"Appuyer sur ${contextMenu} ou sur la touche Menu pour ouvrir le menu contextuel. Se deplacer ensuite vers l'option suivante du menu avec les touches Tab ou Fleche bas. Se deplacer vers l'option precedente avec les touches Maj+Tab ou Fleche haut. Appuyer sur la barre d'espace ou la touche Entree pour selectionner l'option du menu. Appuyer sur la barre d'espace, la touche Entree ou Fleche droite pour ouvrir le sous-menu de l'option selectionnee. Revenir a l'element de menu parent avec la touche Echap ou Fleche gauche. Fermer le menu contextuel avec Echap."},
{name:"Zone de liste de l'editeur",legend:"Dans une liste en menu deroulant, se deplacer vers l'element suivant de la liste avec les touches Tab ou Fleche bas. Se deplacer vers l'element precedent de la liste avec les touches Maj+Tab ou Fleche haut. Appuyer sur la barre d'espace ou sur Entree pour selectionner l'option dans la liste. Appuyer sur Echap pour fermer le menu deroulant."},{name:"Barre du chemin d'elements de l'editeur",legend:"Appuyer sur ${elementsPathFocus} pour naviguer vers la barre du fil d'Ariane des elements. Se deplacer vers le bouton de l'element suivant avec les touches Tab ou Fleche droite. Se deplacer vers le bouton precedent avec les touches Maj+Tab ou Fleche gauche. Appuyer sur la barre d'espace ou sur Entree pour selectionner l'element dans l'editeur."}]},
{name:"Commandes",items:[{name:" Annuler la commande",legend:"Appuyer sur ${undo}"},{name:"Commande restaurer",legend:"Appuyer sur ${redo}"},{name:" Commande gras",legend:"Appuyer sur ${bold}"},{name:" Commande italique",legend:"Appuyer sur ${italic}"},{name:" Commande souligne",legend:"Appuyer sur ${underline}"},{name:" Commande lien",legend:"Appuyer sur ${link}"},{name:" Commande enrouler la barre d'outils",legend:"Appuyer sur ${toolbarCollapse}"},{name:"Commande d'acces a l'element selectionnable precedent",
legend:"Appuyer sur ${accessNextSpace} pour acceder a l'element selectionnable inatteignable le plus proche avant le curseur, par exemple&#160;: deux lignes horizontales adjacentes. Repeter la combinaison de touches pour atteindre les elements selectionnables precedents."},{name:"Commande d'acces a l'element selectionnable suivant",legend:"Appuyer sur ${accessNextSpace} pour acceder a l'element selectionnable inatteignable le plus proche apres le curseur, par exemple&#160;: deux lignes horizontales adjacentes. Repeter la combinaison de touches pour atteindre les elements selectionnables suivants."},
{name:" Aide sur l'accessibilite",legend:"Appuyer sur ${a11yHelp}"}]}],tab:"Tabulation",pause:"Pause",capslock:"Verr. Maj.",escape:"Echap",pageUp:"Page superieure",pageDown:"Page suivante",leftArrow:"Fleche gauche",upArrow:"Fleche haut",rightArrow:"Fleche droite",downArrow:"Fleche basse",insert:"Inser",leftWindowKey:"Touche Windows gauche",rightWindowKey:"Touche Windows droite",selectKey:"Touche Selectionner",numpad0:"0 du pave numerique",numpad1:"1 du pave numerique",numpad2:"2 du pave numerique",
numpad3:"3 du pave numerique",numpad4:"4 du pave numerique",numpad5:"5 du pave numerique",numpad6:"6 du pave numerique",numpad7:"7 du pave numerique",numpad8:"Pave numerique 8",numpad9:"9 du pave numerique",multiply:"Multiplier",add:"Plus",subtract:"Moins",decimalPoint:"Point decimal",divide:"Diviser",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Verr. Num.",scrollLock:"Arret defil.",semiColon:"Point-virgule",equalSign:"Signe egal",
comma:"Virgule",dash:"Tiret",period:"Point",forwardSlash:"Barre oblique",graveAccent:"Accent grave",openBracket:"Parenthese ouvrante",backSlash:"Barre oblique inverse",closeBracket:"Parenthese fermante",singleQuote:"Apostrophe"});