/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","gl",{title:"Instrucions de accesibilidade",contents:"Axuda. Para pechar este dialogo prema ESC.",legend:[{name:"Xeral",items:[{name:"Barra de ferramentas do editor",legend:"Prema ${toolbarFocus} para navegar pola barra de ferramentas. Para moverse polos distintos grupos de ferramentas use as teclas TAB e MAIUS+TAB. Para moverse polas distintas ferramentas use FRECHA DEREITA ou FRECHA ESQUERDA. Prema ESPAZO ou INTRO para activar o boton da barra de ferramentas."},
{name:"Editor de dialogo",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Editor do menu contextual",legend:"Prema ${contextMenu} ou a TECLA MENU para abrir o menu contextual. A seguir movase a seguinte opcion do menu con TAB ou FRECHA ABAIXO. Movase a opcion anterior con MAIUS + TAB ou FRECHA ARRIBA. Prema ESPAZO ou INTRO para seleccionar a opcion do menu. Abra o submenu da opcion actual con ESPAZO ou INTRO ou FRECHA DEREITA. Regrese ao elemento principal do menu con ESC ou FRECHA ESQUERDA. Peche o menu contextual con ESC."},
{name:"Lista do editor",legend:"Dentro dunha lista, movase ao seguinte elemento da lista con TAB ou FRECHA ABAIXO. Movase ao elemento anterior da lista con MAIUS+TAB ou FRECHA ARRIBA. Prema ESPAZO ou INTRO para escoller a opcion da lista. Prema ESC para pechar a lista."},{name:"Barra da ruta ao elemento no editor",legend:"Prema ${elementsPathFocus} para navegar ata os elementos da barra de ruta. Movase ao seguinte elemento boton con TAB ou FRECHA DEREITA. Movase ao boton anterior con MAIUS+TAB ou FRECHA ESQUERDA. Prema ESPAZO ou INTRO para seleccionar o elemento no editor."}]},
{name:"Ordes",items:[{name:"Orde &#171;desfacer&#187;",legend:"Prema ${undo}"},{name:"Orde &#171;refacer&#187;",legend:"Prema ${redo}"},{name:"Orde &#171;negra&#187;",legend:"Prema ${bold}"},{name:"Orde &#171;cursiva&#187;",legend:"Prema ${italic}"},{name:"Orde &#171;sublinar&#187;",legend:"Prema ${underline}"},{name:"Orde &#171;ligazon&#187;",legend:"Prema ${link}"},{name:"Orde &#171;contraer a barra de ferramentas&#187;",legend:"Prema ${toolbarCollapse}"},{name:"Orde &#171;acceder ao anterior espazo en foco&#187;",legend:"Prema ${accessPreviousSpace} para acceder ao espazo mais proximo de foco inalcanzabel anterior ao cursor, por exemplo: dous elementos HR adxacentes. Repita a combinacion de teclas para chegar a espazos de foco distantes."},
{name:"Orde &#171;acceder ao seguinte espazo en foco&#187;",legend:"Prema ${accessNextSpace} para acceder ao espazo mais proximo de foco inalcanzabel posterior ao cursor, por exemplo: dous elementos HR adxacentes. Repita a combinacion de teclas para chegar a espazos de foco distantes."},{name:"Axuda da accesibilidade",legend:"Prema ${a11yHelp}"}]}],tab:"Tabulador",pause:"Pausa",capslock:"Bloq. Maius",escape:"Escape",pageUp:"Paxina arriba",pageDown:"Paxina abaixo",leftArrow:"Frecha esquerda",upArrow:"Frecha arriba",
rightArrow:"Frecha dereita",downArrow:"Frecha abaixo",insert:"Inserir",leftWindowKey:"Tecla Windows esquerda",rightWindowKey:"Tecla Windows dereita",selectKey:"Escolla a tecla",numpad0:"Tec. numerico 0",numpad1:"Tec. numerico 1",numpad2:"Tec. numerico 2",numpad3:"Tec. numerico 3",numpad4:"Tec. numerico 4",numpad5:"Tec. numerico 5",numpad6:"Tec. numerico 6",numpad7:"Tec. numerico 7",numpad8:"Tec. numerico 8",numpad9:"Tec. numerico 9",multiply:"Multiplicar",add:"Sumar",subtract:"Restar",decimalPoint:"Punto decimal",
divide:"Dividir",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Bloq. num.",scrollLock:"Bloq. despraz.",semiColon:"Punto e coma",equalSign:"Signo igual",comma:"Coma",dash:"Guion",period:"Punto",forwardSlash:"Barra inclinada",graveAccent:"Acento grave",openBracket:"Abrir corchete",backSlash:"Barra invertida",closeBracket:"Pechar corchete",singleQuote:"Comina simple"});