/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","hu",{title:"Kisegitő utasitasok",contents:"Sugo tartalmak. A parbeszedablak bezarasahoz nyomjon ESC-et.",legend:[{name:"Altalanos",items:[{name:"Szerkesztő Eszkoztar",legend:"Nyomjon ${toolbarFocus} hogy kijelolje az eszkoztarat. A kovetkező es előző eszkoztar csoporthoz a TAB es SHIFT+TAB-al juthat el. A kovetkező es előző eszkoztar gombhoz a BAL NYIL vagy JOBB NYIL gombbal juthat el. Nyomjon SPACE-t vagy ENTER-t hogy aktivalja az eszkoztar gombot."},{name:"Szerkesző parbeszed ablak",
legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Szerkesztő helyi menu",legend:"Nyomjon ${contextMenu}-t vagy ALKALMAZAS BILLENTYŰT a helyi menu megnyitasahoz. Ezutan a kovetkező menupontra lephet a TAB vagy LEFELE NYILLAL. Az előző opciot a SHIFT+TAB vagy FELFELE NYILLAL erheti el. Nyomjon SPACE-t vagy ENTER-t a menupont kivalasztasahoz. A jelenlegi menupont almenujenek megnyitasahoz nyomjon SPACE-t vagy ENTER-t, vagy JOBB NYILAT. A főmenuhoz valo visszatereshez nyomjon ESC-et vagy BAL NYILAT. A helyi menu bezarasa az ESC billentyűvel lehetseges."},
{name:"Szerkesztő lista",legend:"A listan belul a kovetkező elemre a TAB vagy LEFELE NYILLAL mozoghat. Az előző elem kivalasztasahoz nyomjon SHIFT+TAB-ot vagy FELFELE NYILAT. Nyomjon SPACE-t vagy ENTER-t az elem kivalasztasahoz. Az ESC billentyű megnyomasaval bezarhatja a listat."},{name:"Szerkesztő elem utak sav",legend:"Nyomj ${elementsPathFocus} hogy kijelold a elemek ut savjat. A kovetkező elem gombhoz a TAB-al vagy a JOBB NYILLAL juthatsz el. Az előző gombhoz a SHIFT+TAB vagy BAL NYILLAL mehetsz. A SPACE vagy ENTER billentyűvel kivalaszthatod az elemet a szerkesztőben."}]},
{name:"Parancsok",items:[{name:"Parancs visszavonasa",legend:"Nyomj ${undo}"},{name:"Parancs megismetlese",legend:"Nyomjon ${redo}"},{name:"Felkover parancs",legend:"Nyomjon ${bold}"},{name:"Dőlt parancs",legend:"Nyomjon ${italic}"},{name:"Alahuzott parancs",legend:"Nyomjon ${underline}"},{name:"Link parancs",legend:"Nyomjon ${link}"},{name:"Szerkesztősav osszecsukasa parancs",legend:"Nyomjon ${toolbarCollapse}"},{name:"Hozzaferes az előző fokusz helyhez parancs",legend:"Nyomj ${accessNextSpace} hogy hozzaferj a legkozelebbi elerhetetlen fokusz helyhez a hianyjel előtt, peldaul: ket szomszedos HR elemhez. Ismeteld meg a billentyűkombinaciot hogy megtalald a tavolabbi fokusz helyeket."},
{name:"Hozzaferes a kovetkező fokusz helyhez parancs",legend:"Nyomj ${accessNextSpace} hogy hozzaferj a legkozelebbi elerhetetlen fokusz helyhez a hianyjel utan, peldaul: ket szomszedos HR elemhez. Ismeteld meg a billentyűkombinaciot hogy megtalald a tavolabbi fokusz helyeket."},{name:"Kisegitő sugo",legend:"Nyomjon ${a11yHelp}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"balra nyil",upArrow:"felfele nyil",rightArrow:"jobbra nyil",
downArrow:"lefele nyil",insert:"Insert",leftWindowKey:"bal Windows-billentyű",rightWindowKey:"jobb Windows-billentyű",selectKey:"Billentyű valasztasa",numpad0:"Szambillentyűk 0",numpad1:"Szambillentyűk 1",numpad2:"Szambillentyűk 2",numpad3:"Szambillentyűk 3",numpad4:"Szambillentyűk 4",numpad5:"Szambillentyűk 5",numpad6:"Szambillentyűk 6",numpad7:"Szambillentyűk 7",numpad8:"Szambillentyűk 8",numpad9:"Szambillentyűk 9",multiply:"Szorzas",add:"Hozzaadas",subtract:"Kivonas",decimalPoint:"Tizedespont",
divide:"Osztas",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Pontosvessző",equalSign:"Egyenlősegjel",comma:"Vessző",dash:"Kotőjel",period:"Pont",forwardSlash:"Perjel",graveAccent:"Visszafele dőlő ekezet",openBracket:"Nyito szogletes zarojel",backSlash:"forditott perjel",closeBracket:"Zaro szogletes zarojel",singleQuote:"szimpla idezőjel"});