/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sk",{title:"Inštrukcie pristupnosti",contents:"Pomocny obsah. Pre zatvorenie tohto okna, stlačte ESC.",legend:[{name:"Všeobecne",items:[{name:"Lišta nastrojov editora",legend:"Stlačte ${toolbarFocus} pre navigaciu na lištu nastrojov. Medzi ďalšou a predchadzajucou lištou nastrojov sa pohybujete s TAB a SHIFT+TAB. Medzi ďalšim a predchadzajucim tlačidlom na lište nastrojov sa pohybujete s pravou šipkou a ľavou šipkou. Stlačte medzernik alebo ENTER pre aktivaciu tlačidla lišty nastrojov."},
{name:"Editorovy dialog",legend:"V dialogovom okne stlačte TAB pre presun na ďalši prvok, SHIFT+TAB pre presun na predchadzajuci prvok, ENTER pre odoslanie, ESC pre zrušenie. Keď ma dialogove okno viacero kariet, zoznam kariet dosiahnete buď stlačenim ALT+F10 alebo s TAB v prislušnom poradi kariet. So zameranym zoznamom kariet sa pohybujte k ďalšej alebo predchadzajucej karte cez PRAVU a ĽAVU ŠIPKU."},{name:"Editorove kontextove menu",legend:"Stlačte ${contextMenu} alebo APPLICATION KEY pre otvorenie kontextoveho menu. Potom sa presuvajte na ďalšie možnosti menu s TAB alebo dolnou šipkou. Presunte sa k predchadzajucej možnosti s SHIFT+TAB alebo hornou šipkou. Stlačte medzernik alebo ENTER pre vyber možnosti menu. Otvorte pod-menu danej možnosti s medzernikom, alebo ENTER, alebo pravou šipkou. Vraťte sa spať do položky rodičovskeho menu s ESC alebo ľavou šipkou. Zatvorte kontextove menu s ESC."},
{name:"Editorov box zoznamu",legend:"V boxe zoznamu, presuňte sa na ďalšiu položku v zozname s TAB alebo dolnou šipkou. Presuňte sa k predchadzajucej položke v zozname so SHIFT+TAB alebo hornou šipkou. Stlačte medzernik alebo ENTER pre vyber možnosti zoznamu. Stlačte ESC pre zatvorenie boxu zoznamu."},{name:"Editorove pasmo cesty prvku",legend:"Stlačte ${elementsPathFocus} pre navigovanie na pasmo cesty elementu. Presuňte sa na tlačidlo ďalšieho prvku s TAB alebo pravou šipkou. Presuňte sa k predchadzajucemu tlačidlu s SHIFT+TAB alebo ľavou šipkou. Stlačte medzernik alebo ENTER pre vyber prvku v editore."}]},
{name:"Prikazy",items:[{name:"Vratiť prikazy",legend:"Stlačte ${undo}"},{name:"Nanovo vratiť prikaz",legend:"Stlačte ${redo}"},{name:"Prikaz na stučnenie",legend:"Stlačte ${bold}"},{name:"Prikaz na kurzivu",legend:"Stlačte ${italic}"},{name:"Prikaz na podčiarknutie",legend:"Stlačte ${underline}"},{name:"Prikaz na odkaz",legend:"Stlačte ${link}"},{name:"Prikaz na zbalenie lišty nastrojov",legend:"Stlačte ${toolbarCollapse}"},{name:"Prejsť na predchadzajucu zamerateľnu medzeru prikazu",legend:"Stlačte ${accessPreviousSpace} pre pristup na najbližšie nedosiahnuteľne zamerateľne medzery pred vsuvkuo. Napriklad: dve za sebou iduce horizontalne čiary. Opakujte kombinaciu klavesov pre dosiahnutie vzdialenych zamerateľnych medzier."},
{name:"Prejsť na ďalši ",legend:"Stlačte ${accessNextSpace} pre pristup na najbližšie nedosiahnuteľne zamerateľne medzery po vsuvke. Napriklad: dve za sebou iduce horizontalne čiary. Opakujte kombinaciu klavesov pre dosiahnutie vzdialenych zamerateľnych medzier."},{name:"Pomoc pristupnosti",legend:"Stlačte ${a11yHelp}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Stranka hore",pageDown:"Stranka dole",leftArrow:"Šipka naľavo",upArrow:"Šipka hore",rightArrow:"Šipka napravo",
downArrow:"Šipka dole",insert:"Insert",leftWindowKey:"Ľave Windows tlačidlo",rightWindowKey:"Prave Windows tlačidlo",selectKey:"Tlačidlo Select",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Nasobenie",add:"Sčitanie",subtract:"Odčitanie",decimalPoint:"Desatinna čiarka",divide:"Delenie",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",
f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Bodkočiarka",equalSign:"Rovna sa",comma:"Čiarka",dash:"Pomĺčka",period:"Bodka",forwardSlash:"Lomitko",graveAccent:"Zdorazňovanie prizvuku",openBracket:"Hranata zatvorka otvaracia",backSlash:"Backslash",closeBracket:"Hranata zatvorka zatvaracia",singleQuote:"Jednoduche uvodzovky"});