/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sv",{title:"Hjalpmedelsinstruktioner",contents:"Hjalpinnehall. For att stanga denna dialogruta trycker du pa ESC.",legend:[{name:"Allmant",items:[{name:"Editor verktygsfalt",legend:"Tryck pa ${toolbarFocus} for att navigera till verktygsfaltet. Flytta till nasta och foregaende verktygsfaltsgrupp med TAB och SHIFT+TAB. Flytta till nasta och foregaende knapp i verktygsfaltet med HOGERPIL eller VANSTERPIL. Tryck SPACE eller ENTER for att aktivera knappen i verktygsfaltet."},
{name:"Dialogeditor",legend:"Inuti en dialogruta, tryck TAB for att navigera till nasta falt i dialogrutan, tryck SKIFT+TAB for att flytta till foregaende falt, tryck ENTER for att skicka. Du avbryter och stanger dialogen med ESC. For dialogrutor som har flera flikar, tryck ALT+F10 eller TAB for att navigera till fliklistan. med fliklistan vald flytta till nasta och foregaende flik med HOGER- eller VANSTERPIL."},{name:"Editor for innehallsmeny",legend:"Tryck pa $ {contextMenu} eller PROGRAMTANGENTEN for att oppna snabbmenyn. Flytta sedan till nasta menyalternativ med TAB eller NEDPIL. Flytta till foregaende alternativ med SHIFT + TABB eller UPPIL. Tryck Space eller ENTER for att valja menyalternativ. Oppna undermeny av nuvarande alternativ med SPACE eller ENTER eller HOGERPIL. Ga tillbaka till overordnade menyalternativ med ESC eller VANSTERPIL. Stang snabbmenyn med ESC."},
{name:"Editor for list-box",legend:"Inuti en list-box, ga till nasta listobjekt med TAB eller NEDPIL. Flytta till foregaende listobjekt med SHIFT+TAB eller UPPIL. Tryck SPACE eller ENTER for att valja listan alternativet. Tryck ESC for att stanga list-boxen."},{name:"Editor for elementens sokvag",legend:"Tryck pa ${elementsPathFocus} for att navigera till verktygsfaltet for elementens sokvagar. Flytta till nasta elementknapp med TAB eller HOGERPIL. Flytta till foregaende knapp med SKIFT+TAB eller VANSTERPIL. Tryck SPACE eller ENTER for att valja element i redigeraren."}]},
{name:"Kommandon",items:[{name:"Angra kommando",legend:"Tryck pa ${undo}"},{name:"Gor om kommando",legend:"Tryck pa ${redo}"},{name:"Kommandot fet stil",legend:"Tryck pa ${bold}"},{name:"Kommandot kursiv",legend:"Tryck pa ${italic}"},{name:"Kommandot understruken",legend:"Tryck pa ${underline}"},{name:"Kommandot lank",legend:"Tryck pa ${link}"},{name:"Verktygsfalt Dolj kommandot",legend:"Tryck pa ${toolbarCollapse}"},{name:"Ga till foregaende fokus plats",legend:"Tryck pa ${accessPreviousSpace} for att ga till narmast onabara utrymme fore markoren, exempel: tva intilliggande HR element. Repetera tangentkombinationen for att ga till nasta."},
{name:"Tillga nasta fokuskommandots utrymme",legend:"Tryck ${accessNextSpace} pa for att komma at den narmaste onabar fokus utrymme efter cirkumflex, till exempel: tva intilliggande HR element. Upprepa tangentkombinationen for att na avlagsna fokus utrymmen."},{name:"Hjalp om tillganglighet",legend:"Tryck ${a11yHelp}"}]}],tab:"Tab",pause:"Paus",capslock:"Caps lock",escape:"Escape",pageUp:"Sida Up",pageDown:"Sida Ned",leftArrow:"Vansterpil",upArrow:"Uppil",rightArrow:"Hogerpil",downArrow:"Nedatpil",
insert:"Infoga",leftWindowKey:"Vanster Windowstangent",rightWindowKey:"Hoger Windowstangent",selectKey:"Valj tangent",numpad0:"Nummer 0",numpad1:"Nummer 1",numpad2:"Nummer 2",numpad3:"Nummer 3",numpad4:"Nummer 4",numpad5:"Nummer 5",numpad6:"Nummer 6",numpad7:"Nummer 7",numpad8:"Nummer 8",numpad9:"Nummer 9",multiply:"Multiplicera",add:"Addera",subtract:"Minus",decimalPoint:"Decimalpunkt",divide:"Dividera",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",
numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semikolon",equalSign:"Lika med tecken",comma:"Komma",dash:"Minus",period:"Punkt",forwardSlash:"Snedstreck framat",graveAccent:"Accent",openBracket:"Oppningsparentes",backSlash:"Snedstreck bakat",closeBracket:"Slutparentes",singleQuote:"Enkelt Citattecken"});