/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","vi",{title:"Hướng dẫn trợ năng",contents:"Nội dung Hỗ trợ. Nhấn ESC để đong hộp thoại.",legend:[{name:"Chung",items:[{name:"Thanh cong cụ soạn thảo",legend:"Nhấn ${toolbarFocus} để điều hướng đến thanh cong cụ. Nhấn TAB va SHIFT+TAB để chuyển đến nhom thanh cong cụ khac. Nhấn MŨI TEN PHẢI hoặc MŨI TEN TRAI để chuyển sang nut khac tren thanh cong cụ. Nhấn PHIM CACH hoặc ENTER để kich hoạt nut tren thanh cong cụ."},{name:"Hộp thoại Bien t",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"Trinh đơn Ngữ cảnh cBộ soạn thảo",legend:"Nhấn ${contextMenu} hoặc PHIM ỨNG DỤNG để mở thực đơn ngữ cảnh. Sau đo nhấn TAB hoặc MŨI TEN XUỐNG để di chuyển đến tuỳ chọn tiếp theo của thực đơn. Nhấn SHIFT+TAB hoặc MŨI TEN LEN để quay lại tuỳ chọn trước. Nhấn DẤU CACH hoặc ENTER để chọn tuỳ chọn của thực đơn. Nhấn DẤU CACH hoặc ENTER hoặc MŨI TEN SANG PHẢI để mở thực đơn con của tuỳ chọn hiện tại. Nhấn ESC hoặc MŨI TEN SANG TRAI để quay trở lại thực đơn gốc. Nhấn ESC để đong thực đơn ngữ cảnh."},
{name:"Hộp danh sach trinh bien tập",legend:"Trong một danh sach chọn, di chuyển đối tượng tiếp theo với phim TAB hoặc phim mũi ten hướng xuống. Di chuyển đến đối tượng trước đo bằng cach nhấn tổ hợp phim SHIFT+TAB hoặc mũi ten hướng len. Phim khoảng cach hoặc phim ENTER để chọn cac tuy chọn trong danh sach. Nhấn phim ESC để đong lại danh sach chọn."},{name:"Thanh đường dẫn cac đối tượng",legend:"Nhấn ${elementsPathFocus} để điều hướng cac đối tượng trong thanh đường dẫn. Di chuyển đến đối tượng tiếp theo bằng phim TAB hoặc phim mũi ten ben phải. Di chuyển đến đối tượng trước đo bằng tổ hợp phim SHIFT+TAB hoặc phim mũi ten ben trai. Nhấn phim khoảng cach hoặc ENTER để chọn đối tượng trong trinh soạn thảo."}]},
{name:"Lệnh",items:[{name:"Lam lại lện",legend:"Ấn ${undo}"},{name:"Lam lại lệnh",legend:"Ấn ${redo}"},{name:"Lệnh in đậm",legend:"Ấn ${bold}"},{name:"Lệnh in nghieng",legend:"Ấn ${italic}"},{name:"Lệnh gạch dưới",legend:"Ấn ${underline}"},{name:"Lệnh lien kết",legend:"Nhấn ${link}"},{name:"Lệnh hiển thị thanh cong cụ",legend:"Nhấn${toolbarCollapse}"},{name:"Truy cập đến lệnh tập trung vao khoảng cach trước đo",legend:"Ấn ${accessPreviousSpace} để truy cập đến phần tập trung khoảng cach sau phần con sot lại của khoảng cach gần nhất vốn khong tac động đến được , thi dụ: hai yếu tố điều chỉnh HR. Lặp lại cac phim kết họep nay để vươn đến phần khoảng cach."},
{name:"Truy cập phần đối tượng lệnh khoảng trống",legend:"Ấn ${accessNextSpace} để truy cập đến phần tập trung khoảng cach sau phần con sot lại của khoảng cach gần nhất vốn khong tac động đến được , thi dụ: hai yếu tố điều chỉnh HR. Lặp lại cac phim kết họep nay để vươn đến phần khoảng cach."},{name:"Trợ giup lien quan",legend:"Nhấn ${a11yHelp}"}]}],tab:"Phim Tab",pause:"Phim Pause",capslock:"Phim Caps Lock",escape:"Phim Escape",pageUp:"Phim Page Up",pageDown:"Phim Page Down",leftArrow:"Phim Left Arrow",
upArrow:"Phim Up Arrow",rightArrow:"Phim Right Arrow",downArrow:"Phim Down Arrow",insert:"Chen",leftWindowKey:"Phim Left Windows",rightWindowKey:"Phim Right Windows ",selectKey:"Chọn phim",numpad0:"Phim 0",numpad1:"Phim 1",numpad2:"Phim 2",numpad3:"Phim 3",numpad4:"Phim 4",numpad5:"Phim 5",numpad6:"Phim 6",numpad7:"Phim 7",numpad8:"Phim 8",numpad9:"Phim 9",multiply:"Nhan",add:"Them",subtract:"Trừ",decimalPoint:"Điểm số thập phan",divide:"Chia",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",
f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Dấu chấm phẩy",equalSign:"Đăng nhập bằng",comma:"Dấu phẩy",dash:"Dấu gạch ngang",period:"Phim .",forwardSlash:"Phim /",graveAccent:"Phim `",openBracket:"Open Bracket",backSlash:"Dấu gạch cheo ngược",closeBracket:"Gần gia đỡ",singleQuote:"Trich dẫn"});